### ISSUE TITLE
도리 고 님에게 추가 기능 요청을 드립니다

### ISSUE THREAD

**Issue by cv01miku** [godori/banner-maker#1]
- [x] input:focus 일 때, placeholder 텍스트를 안보이게 해주세요
- [x] 글자를 길게 입력해서 캔버스 영역을 초과할 경우, 자동으로 줄 바꿈이 되게 해주세요
- [x] Canvas에 적당한 padding 이 있으면 좋을 것 같아요
- [x] Hex Color 를 사용자가 직접 입력할 수 있게 해주세요
- [x] 그럴싸한 웹 폰트를 적용해 주세요 👻([이 폰트들](https://developer.apple.com/fonts/) 괜찮습니다)

**Comment by godori** [comment]
padding은 안쪽을 말씀하시는 것인지 잘 모르겠지만 캔버스 바깥에 적당한 margin을 추가했습니다.

**Comment by cv01miku** [comment]
호호 확인했습니다 배포도 하셨네요!
미 해결 부분에 대해 여유있을때 풀 리퀘도 한번 올려 보겠습니다😎

**Comment by godori** [comment]
반영 완료
